export const SUCCESS_SYLLABUS_PROGRESS_RETRIVAL = "SUCCESS_SYLLABUS_PROGRESS_RETRIVAL";
export const FAILURE_PROGRESS_RETRIVAL = "FAILURE_PROGRESS_RETRIVAL";
export const SELECTED_SYLLABUS = "SELECTED_SYLLABUS";
export const SET_UNITS_PROGRESS = "SET_UNITS_PROGRESS";
